#
# /etc/pacman.conf  (build-time configuration for Hyper OS)
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Custom repository: packages staged from the AUR at build time
# (calamares, paru, quickshell, matugen ...). See scripts/stage-aur.sh.
[hyper]
SigLevel = Optional TrustAll
Server = file:///home/paret/hyper-os/localrepo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
