# Hyper OS — GRUB for both BIOS and UEFI.
---
efiBootLoader: "grub"

kernelParams: [ "quiet" ]

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

efiBootloaderId: "HyperOS"
installEFIFallback: true
installHybridGRUB: true