import os
import subprocess

import libcalamares

GPU_VENDORS = (
    ("nvidia", "10de"),
    ("amd", "1002"),
    ("intel", "8086"),
)

GPU_ENV = {
    "nvidia": {
        "NVD_BACKEND": "direct",
        "GBM_BACKEND": "nvidia-drm",
        "__GLX_VENDOR_LIBRARY_NAME": "nvidia",
        "LIBVA_DRIVER_NAME": "nvidia",
        "WLR_NO_HARDWARE_CURSORS": "1",
    },
    "amd": {
        "LIBVA_DRIVER_NAME": "radeonsi",
    },
    "intel": {
        "LIBVA_DRIVER_NAME": "iHD",
    },
}


def _lspci():
    try:
        return (subprocess.run(["lspci"], capture_output=True, text=True).stdout or "").splitlines()
    except Exception as exc:
        libcalamares.utils.warning("hypergpu: could not run lspci: %s" % exc)
        return []


def _detect():
    for name, vendor in GPU_VENDORS:
        for line in _lspci():
            low = line.lower()
            if ("vga" in low or "3d controller" in low) and ("[%s:" % vendor) in low:
                return name
    return None


def run():
    root = libcalamares.globalstorage.value("rootMountPoint") or ""
    gpu = _detect()

    if not gpu:
        libcalamares.utils.debug("hypergpu: no discrete/hybrid GPU detected, keeping defaults")
        return None

    libcalamares.utils.debug("hypergpu: detected %s GPU" % gpu)

    env_dir = os.path.join(root, "etc", "environment.d")
    os.makedirs(env_dir, exist_ok=True)
    lines = ["# GPU detection for Hyper OS (auto-generated by the installer)", "# vendor: %s" % gpu]
    lines += ["%s=%s" % (key, value) for key, value in sorted(GPU_ENV[gpu].items())]
    with open(os.path.join(env_dir, "99-hyper-gpu.conf"), "w") as handle:
        handle.write("\n".join(lines) + "\n")

    hyper_dir = os.path.join(root, "etc", "hyper")
    os.makedirs(hyper_dir, exist_ok=True)
    with open(os.path.join(hyper_dir, "gpu"), "w") as handle:
        handle.write(gpu + "\n")

    return None