[General]
Numlock=on
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
# Theme lives at /usr/share/sddm/themes/hyper-bolt
Current=hyper-bolt

[Users]
DefaultSession=hyper

[Wayland]
EnableHiDPI=true